name: Test Windows Runner

on:
  workflow_dispatch:
    branches: [master]
permissions:
  contents: read  

jobs:
  test:
    runs-on: windows-latest
    name: CI Build
    steps:
    - name: Test Action
      uses: irongut/CodeCoverageSummary@master
      with:
        filename: '/app/sample.coverage.xml'
        badge: 'true'
